name = "MinimalRVA"
license = "MIT"
licenselink = "https://github.com/rvasdug/minimalrva/blob/master/LICENSE.md"
description = "Personal blog theme powered by Hugo"
homepage = "http://github.com/rvasdug/minimalrva/"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Sujith Paul"
  homepage = "https://rvasdug.github.io/"
